#!/usr/bin/env bash
#
# Render the AUR PKGBUILD for a released version, for the `rad-backup-bin` package.
#
#   ./packaging/aur/render.sh 0.1.0 > PKGBUILD
set -euo pipefail

VERSION="${1:?usage: render.sh <version>}"
BASE="https://github.com/maninak/radicle-backup/releases/download/v$VERSION"

sums="$(curl -fsSL "$BASE/sha256sums.txt")"
digest() { echo "$sums" | awk -v f="rad-backup-$1.tar.gz" '$2 == f || $2 == "*"f { print $1; exit }'; }

cat <<EOF
# Generated by packaging/aur/render.sh. Do not edit by hand.
# Maintainer: Konstantinos Maninakis <info@radicle.tools>
pkgname=rad-backup-bin
pkgver=$VERSION
pkgrel=1
pkgdesc="Back up, restore and migrate a Radicle identity, node state and repositories"
arch=('x86_64' 'aarch64')
url="https://github.com/maninak/radicle-backup"
license=('MIT' 'Apache-2.0')
depends=('git')
optdepends=('age: decrypt archives by hand' 'radicle: the node these archives are of')
provides=('rad-backup')
conflicts=('rad-backup')
source_x86_64=("\$pkgname-\$pkgver-x86_64.tar.gz::$BASE/rad-backup-x86_64-unknown-linux-musl.tar.gz")
source_aarch64=("\$pkgname-\$pkgver-aarch64.tar.gz::$BASE/rad-backup-aarch64-unknown-linux-musl.tar.gz")
sha256sums_x86_64=('$(digest x86_64-unknown-linux-musl)')
sha256sums_aarch64=('$(digest aarch64-unknown-linux-musl)')

package() {
  cd "\$srcdir/rad-backup-\$CARCH"* 2>/dev/null || cd "\$srcdir"/rad-backup-*
  install -Dm755 rad-backup "\$pkgdir/usr/bin/rad-backup"
  install -Dm644 LICENSE-MIT "\$pkgdir/usr/share/licenses/\$pkgname/LICENSE-MIT"
  install -Dm644 LICENSE-APACHE "\$pkgdir/usr/share/licenses/\$pkgname/LICENSE-APACHE"
  install -Dm644 README.md "\$pkgdir/usr/share/doc/\$pkgname/README.md"
  [ -f generated/rad-backup.1 ] && install -Dm644 generated/rad-backup.1 "\$pkgdir/usr/share/man/man1/rad-backup.1"
  [ -f generated/rad-backup.bash ] && install -Dm644 generated/rad-backup.bash "\$pkgdir/usr/share/bash-completion/completions/rad-backup"
  [ -f generated/_rad-backup ] && install -Dm644 generated/_rad-backup "\$pkgdir/usr/share/zsh/site-functions/_rad-backup"
  [ -f generated/rad-backup.fish ] && install -Dm644 generated/rad-backup.fish "\$pkgdir/usr/share/fish/vendor_completions.d/rad-backup.fish"
  true
}
EOF
