#!/usr/bin/env bash
#
# Render the Homebrew formula for a released version.
#
#   ./packaging/homebrew/render.sh 0.1.0 > rad-backup.rb
#
# The checksums come from the release's own sha256sums.txt, so the formula cannot claim a
# digest that no published artefact has.
set -euo pipefail

VERSION="${1:?usage: render.sh <version>}"
BASE="https://github.com/maninak/radicle-backup/releases/download/v$VERSION"

sums="$(curl -fsSL "$BASE/sha256sums.txt")"
digest() { echo "$sums" | awk -v f="rad-backup-$1.tar.gz" '$2 == f || $2 == "*"f { print $1; exit }'; }

cat <<EOF
# Generated by packaging/homebrew/render.sh. Do not edit by hand.
class RadBackup < Formula
  desc "Back up, restore and migrate a Radicle identity, node state and repositories"
  homepage "https://github.com/maninak/radicle-backup"
  version "$VERSION"
  license any_of: ["MIT", "Apache-2.0"]

  depends_on "git"

  on_macos do
    on_arm do
      url "$BASE/rad-backup-aarch64-apple-darwin.tar.gz"
      sha256 "$(digest aarch64-apple-darwin)"
    end
    on_intel do
      url "$BASE/rad-backup-x86_64-apple-darwin.tar.gz"
      sha256 "$(digest x86_64-apple-darwin)"
    end
  end

  on_linux do
    on_arm do
      url "$BASE/rad-backup-aarch64-unknown-linux-musl.tar.gz"
      sha256 "$(digest aarch64-unknown-linux-musl)"
    end
    on_intel do
      url "$BASE/rad-backup-x86_64-unknown-linux-musl.tar.gz"
      sha256 "$(digest x86_64-unknown-linux-musl)"
    end
  end

  def install
    bin.install "rad-backup"
    man1.install "generated/rad-backup.1" if File.exist?("generated/rad-backup.1")
    bash_completion.install "generated/rad-backup.bash" => "rad-backup" if File.exist?("generated/rad-backup.bash")
    zsh_completion.install "generated/_rad-backup" if File.exist?("generated/_rad-backup")
    fish_completion.install "generated/rad-backup.fish" if File.exist?("generated/rad-backup.fish")
    doc.install "README.md", "ARCHIVE-FORMAT.md", "SECURITY.md", "CHANGELOG.md"
  end

  def caveats
    <<~EOS
      Installed on PATH as rad-backup, so `rad backup` works too.
      Start with:  rad backup doctor
    EOS
  end

  test do
    assert_match "rad-backup $VERSION", shell_output("#{bin}/rad-backup --version")
  end
end
EOF
